name: deploy-to-website
on: [push]
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ secrets.APP_PATH }}
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ${{ secrets.CONDA_ENV_NAME }}
        python-version: 3.10
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Deploy application
      run:  systemctl restart unused-item-app-service
